version = 2

[[services]]
  name = "web"
  image = "luluzao/dockersiteluisao:latest"
  root = "src"

  [services.build]
    command = "npm install && npm run build"

  [services.start]
    command = "npm start"
